version: 2.1

jobs:
  do_thing:
    parameters:
      step_to_run:
        type: string
        default: "build"
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: run step
          command: yarn "<< parameters.step_to_run >>"
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
              - ./node_modules

workflows:
  test:
    jobs:
      - do_thing:
          name: lint
          step_to_run: lint
      - do_thing:
          name: build
          step_to_run: build
      - do_thing:
          name: test
          step_to_run: test

